apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: i6dr50fek-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/i6dr50fek-java-quarkus-gitops